//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoWCFClient.CalcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stProg", ReplyAction="http://tempuri.org/IService1/stProgResponse")]
        demoWCFClient.CalcServiceReference.stProgResponse stProg(demoWCFClient.CalcServiceReference.stProgRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stProg", ReplyAction="http://tempuri.org/IService1/stProgResponse")]
        System.Threading.Tasks.Task<demoWCFClient.CalcServiceReference.stProgResponse> stProgAsync(demoWCFClient.CalcServiceReference.stProgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stProg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class stProgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        public stProgRequest() {
        }
        
        public stProgRequest(string log, string pass) {
            this.log = log;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stProgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class stProgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool stProgResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sec;
        
        public stProgResponse() {
        }
        
        public stProgResponse(bool stProgResult, int sec) {
            this.stProgResult = stProgResult;
            this.sec = sec;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : demoWCFClient.CalcServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<demoWCFClient.CalcServiceReference.IService1>, demoWCFClient.CalcServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        demoWCFClient.CalcServiceReference.stProgResponse demoWCFClient.CalcServiceReference.IService1.stProg(demoWCFClient.CalcServiceReference.stProgRequest request) {
            return base.Channel.stProg(request);
        }
        
        public bool stProg(string log, string pass, out int sec) {
            demoWCFClient.CalcServiceReference.stProgRequest inValue = new demoWCFClient.CalcServiceReference.stProgRequest();
            inValue.log = log;
            inValue.pass = pass;
            demoWCFClient.CalcServiceReference.stProgResponse retVal = ((demoWCFClient.CalcServiceReference.IService1)(this)).stProg(inValue);
            sec = retVal.sec;
            return retVal.stProgResult;
        }
        
        public System.Threading.Tasks.Task<demoWCFClient.CalcServiceReference.stProgResponse> stProgAsync(demoWCFClient.CalcServiceReference.stProgRequest request) {
            return base.Channel.stProgAsync(request);
        }
    }
}
