//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoWCFClient.CalcServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubData", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class SubData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A {
            get {
                return this.AField;
            }
            set {
                if ((this.AField.Equals(value) != true)) {
                    this.AField = value;
                    this.RaisePropertyChanged("A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int B {
            get {
                return this.BField;
            }
            set {
                if ((this.BField.Equals(value) != true)) {
                    this.BField = value;
                    this.RaisePropertyChanged("B");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Mult", ReplyAction="http://tempuri.org/IService1/MultResponse")]
        int Mult(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Mult", ReplyAction="http://tempuri.org/IService1/MultResponse")]
        System.Threading.Tasks.Task<int> MultAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sub", ReplyAction="http://tempuri.org/IService1/SubResponse")]
        int Sub(demoWCFClient.CalcServiceReference.SubData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sub", ReplyAction="http://tempuri.org/IService1/SubResponse")]
        System.Threading.Tasks.Task<int> SubAsync(demoWCFClient.CalcServiceReference.SubData data);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (DivInputMessage) сообщения DivInputMessage не соответствует значению по умолчанию (Div).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Div", ReplyAction="http://tempuri.org/IService1/DivResponse")]
        demoWCFClient.CalcServiceReference.DivOutputMessage Div(demoWCFClient.CalcServiceReference.DivInputMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Div", ReplyAction="http://tempuri.org/IService1/DivResponse")]
        System.Threading.Tasks.Task<demoWCFClient.CalcServiceReference.DivOutputMessage> DivAsync(demoWCFClient.CalcServiceReference.DivInputMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DivInputMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DivInputMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int B;
        
        public DivInputMessage() {
        }
        
        public DivInputMessage(string Header, int A, int B) {
            this.Header = Header;
            this.A = A;
            this.B = B;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DivOutputMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DivOutputMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Result;
        
        public DivOutputMessage() {
        }
        
        public DivOutputMessage(string Header, int Result) {
            this.Header = Header;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : demoWCFClient.CalcServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<demoWCFClient.CalcServiceReference.IService1>, demoWCFClient.CalcServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int Mult(int a, int b) {
            return base.Channel.Mult(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultAsync(int a, int b) {
            return base.Channel.MultAsync(a, b);
        }
        
        public int Sub(demoWCFClient.CalcServiceReference.SubData data) {
            return base.Channel.Sub(data);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(demoWCFClient.CalcServiceReference.SubData data) {
            return base.Channel.SubAsync(data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        demoWCFClient.CalcServiceReference.DivOutputMessage demoWCFClient.CalcServiceReference.IService1.Div(demoWCFClient.CalcServiceReference.DivInputMessage request) {
            return base.Channel.Div(request);
        }
        
        public int Div(ref string Header, int A, int B) {
            demoWCFClient.CalcServiceReference.DivInputMessage inValue = new demoWCFClient.CalcServiceReference.DivInputMessage();
            inValue.Header = Header;
            inValue.A = A;
            inValue.B = B;
            demoWCFClient.CalcServiceReference.DivOutputMessage retVal = ((demoWCFClient.CalcServiceReference.IService1)(this)).Div(inValue);
            Header = retVal.Header;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<demoWCFClient.CalcServiceReference.DivOutputMessage> demoWCFClient.CalcServiceReference.IService1.DivAsync(demoWCFClient.CalcServiceReference.DivInputMessage request) {
            return base.Channel.DivAsync(request);
        }
        
        public System.Threading.Tasks.Task<demoWCFClient.CalcServiceReference.DivOutputMessage> DivAsync(string Header, int A, int B) {
            demoWCFClient.CalcServiceReference.DivInputMessage inValue = new demoWCFClient.CalcServiceReference.DivInputMessage();
            inValue.Header = Header;
            inValue.A = A;
            inValue.B = B;
            return ((demoWCFClient.CalcServiceReference.IService1)(this)).DivAsync(inValue);
        }
    }
}
